-- ============================================================
-- 0006_disputes_jury_evidence.sql
-- Evidence storage metadata, jury cases, assignments,
-- votes, and juror flags.
--
-- Applied gaps:
--   GAP-13  jury_cases.evidence_a_id / evidence_b_id
--           establishes the blind-packet mapping at case creation
--   GAP-12  jury_flags table (distinct from moderation_reports)
-- ============================================================

-- ── evidence_objects ─────────────────────────────────────────
-- Evidence is post-MVP for primary DARE type, but disputes and
-- future evidence DAREs require this schema now.
-- Media lives in a private Supabase Storage bucket.
-- Access is through short-lived signed URLs generated by Edge Functions only.
create table evidence_objects (
  id                  uuid primary key default gen_random_uuid(),
  dare_id             uuid not null references dares(id) on delete cascade,
  user_id             uuid not null references profiles(id) on delete restrict,
  storage_bucket      text not null,
  storage_path        text not null,
  content_hash        text,
  media_type          text not null,
  byte_size           bigint,
  capture_started_at  timestamptz,
  capture_ended_at    timestamptz,
  uploaded_at         timestamptz,
  status              text not null default 'uploaded',
  metadata            jsonb not null default '{}',
  created_at          timestamptz not null default now(),

  unique (storage_bucket, storage_path),
  constraint evidence_objects_status_valid
    check (status in ('pending','uploaded','processing','accepted','rejected','deleted')),
  constraint evidence_objects_byte_size_valid
    check (byte_size is null or byte_size >= 0)
);

create index evidence_objects_dare_id_idx on evidence_objects (dare_id);
create index evidence_objects_user_id_idx on evidence_objects (user_id);
create index evidence_objects_status_idx  on evidence_objects (status);

-- ── jury_cases ───────────────────────────────────────────────
-- GAP-13: evidence_a_id and evidence_b_id establish the blind
-- side mapping before jurors are assigned. Set by file_dispute RPC.
create table jury_cases (
  id                uuid primary key default gen_random_uuid(),
  dare_id           uuid not null references dares(id) on delete restrict,
  opened_by_user_id uuid not null references profiles(id) on delete restrict,
  status            text not null default 'filed',
  reason            text not null,
  votes_needed      integer not null default 3,
  verdict           text,
  evidence_a_id     uuid references evidence_objects(id) on delete restrict, -- GAP-13
  evidence_b_id     uuid references evidence_objects(id) on delete restrict, -- GAP-13
  opened_at         timestamptz not null default now(),
  closed_at         timestamptz,
  escalated_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint jury_cases_reason_len
    check (char_length(reason) between 10 and 3000),
  constraint jury_cases_votes_needed_valid
    check (votes_needed in (3,5,7)),
  constraint jury_cases_status_valid check (status in (
    'filed','accepted_for_review','jury_assignment','jury_voting',
    'verdict_reached','settlement_pending','closed','escalated','voided'
  )),
  constraint jury_cases_verdict_valid
    check (verdict is null or verdict in ('A','B','void','escalate','uphold','overturn'))
);

create index jury_cases_dare_id_idx
  on jury_cases (dare_id);
create index jury_cases_status_opened_idx
  on jury_cases (status, opened_at desc);
create index jury_cases_opened_by_user_idx
  on jury_cases (opened_by_user_id, opened_at desc);

create trigger trg_jury_cases_updated_at
  before update on jury_cases
  for each row execute function set_updated_at();

-- ── jury_assignments ─────────────────────────────────────────
-- blind_side_mapping: jsonb that maps {'A': 'issuer'|'challenger'} for
-- this juror — randomized per assignment so vote buying is harder.
create table jury_assignments (
  id              uuid primary key default gen_random_uuid(),
  jury_case_id    uuid not null references jury_cases(id) on delete cascade,
  juror_id        uuid not null references profiles(id) on delete restrict,
  status          text not null default 'assigned',
  blind_side_mapping jsonb not null default '{}',
  assigned_at     timestamptz not null default now(),
  claimed_at      timestamptz,
  due_at          timestamptz,
  completed_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  unique (jury_case_id, juror_id),
  constraint jury_assignments_status_valid
    check (status in ('assigned','claimed','completed','expired','declined','cancelled'))
);

create index jury_assignments_juror_status_idx
  on jury_assignments (juror_id, status);
create index jury_assignments_case_status_idx
  on jury_assignments (jury_case_id, status);
create index jury_assignments_due_idx
  on jury_assignments (due_at) where status in ('assigned','claimed');

create trigger trg_jury_assignments_updated_at
  before update on jury_assignments
  for each row execute function set_updated_at();

-- ── jury_votes ───────────────────────────────────────────────
-- Immutable once inserted. Tally is hidden from participants until verdict.
create table jury_votes (
  id            uuid primary key default gen_random_uuid(),
  jury_case_id  uuid not null references jury_cases(id) on delete cascade,
  juror_id      uuid not null references profiles(id) on delete restrict,
  vote          text not null,
  rationale     text not null,
  created_at    timestamptz not null default now(),

  unique (jury_case_id, juror_id),
  constraint jury_votes_vote_valid
    check (vote in ('A','B','void','escalate')),
  constraint jury_votes_rationale_len
    check (char_length(rationale) between 20 and 3000)
);

create index jury_votes_case_idx  on jury_votes (jury_case_id);
create index jury_votes_juror_idx on jury_votes (juror_id, created_at desc);

-- ── jury_flags (GAP-12) ──────────────────────────────────────
-- Juror flags a case as unsuitable for jury resolution
-- (missing evidence, constitutional ambiguity, etc.).
-- Distinct from moderation_reports which handles user-content reports.
create table jury_flags (
  id            uuid primary key default gen_random_uuid(),
  jury_case_id  uuid not null references jury_cases(id) on delete cascade,
  flagged_by    uuid not null references profiles(id) on delete restrict,
  reason        text not null,
  reviewed      boolean not null default false,
  reviewed_by   uuid references profiles(id) on delete set null,
  review_note   text,
  created_at    timestamptz not null default now(),

  constraint jury_flags_reason_len
    check (char_length(reason) between 10 and 2000)
);

create index jury_flags_case_idx on jury_flags (jury_case_id);
create index jury_flags_reviewed_idx on jury_flags (reviewed) where reviewed = false;
